apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gocolor.fullname" . }}
  labels:
    {{- include "gocolor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gocolor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gocolor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
          - "-addr=:8080"
          {{- if .Values.gocolorEnv }}
          env:
          {{- if .Values.gocolorEnv.account }}
          - name: GOCOLOR_ACCOUNT
            value: {{ .Values.gocolorEnv.account }}
          {{- end }}
          {{- if .Values.gocolorEnv.color }}
          - name: GOCOLOR_COLOR
            value: {{ .Values.gocolorEnv.color }}
          {{- end }}
          {{- if .Values.gocolorEnv.region }}
          - name: GOCOLOR_REGION
            value: {{ .Values.gocolorEnv.region }}
          {{- end }}
          {{- end }}
          ports:
            - name: http-service
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /info
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            failureThreshold: 2
            successThreshold: 1
            periodSeconds: 15 # this is at least as long as failureThreshold * periodSeconds on readinessProbe
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /info
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 4
            timeoutSeconds: 3
