apiVersion: v1
kind: Service
metadata:
  name: {{ include "gocolor.fullname" . }}
  labels:
    {{- include "gocolor.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-service
      name: http-service
  selector:
    {{- include "gocolor.selectorLabels" . | nindent 4 }}
