apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gocolor-native
  name: gocolor-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gocolor-native
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gocolor-native
    spec:
      containers:
      - name: gocolor-native
        image: jwenz723/gocolor:sha-cac4dd6
        args:
        - "-addr=:8080"
        env:
        - name: GOCOLOR_ACCOUNT
          value: "native account"
        - name: GOCOLOR_COLOR
          value: "yellow"
        - name: GOCOLOR_REGION
          value: "native region"
        ports:
        - name: http-service
          containerPort: 8080
