apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: gocolor-native
  name: gocolor-native
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gocolor-native
  template:
    metadata:
      labels:
        name: gocolor-native
    spec:
      containers:
      - name: gocolor-native
        image: jwenz723/gocolor:sha-cac4dd6
        args:
        - "-addr=:8080"
        ports:
        - name: http-service
          containerPort: 8080
