apiVersion: v1
kind: Service
metadata:
  labels:
    name: gocolor-native
  name: gocolor-native
spec:
  ports:
    - name: http-service
      port: 8080
      targetPort: http-service
  selector:
    name: gocolor-native
