# Default values for gocolor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jwenz723/gocolor
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  port: 8080

# gocolorEnv contains a map of variables to be applied to the gocolor deployment as env variables. Note that the map
# keys are not dynamic, you must use the predefined keys.
gocolorEnv:
  account: null
  color: null
  region: null