# This will load the contents of k8s/jsonnet/main into argo as an application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gocolor-jsonnet
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/jwenz723/gocolor.git
    targetRevision: HEAD
    path: k8s/jsonnet/main
    directory:
      jsonnet:
        libs:
          - k8s/jsonnet/vendor
        tlas:
          - name: name
            value: "gocolor-jsonnet"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
