apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gocolor
  name: gocolor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gocolor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gocolor
    spec:
      containers:
      - name: gocolor
        image: jwenz723/gocolor:sha-cac4dd6
        args:
        - "-addr=:8080"
        ports:
        - name: http-service
          containerPort: 8080
