apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gocolor.fullname" . }}
  labels:
    {{- include "gocolor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gocolor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gocolor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
          - "-addr=:8080"
          ports:
            - name: http-service
              containerPort: {{ .Values.service.port }}
