name: release-chart
on:
  push:
    tags: 'chart-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: calculate git hash
        run: echo "::set-output name=GITHASH::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Update Chart.yaml
        run: |
          ls
          echo "hash: $GITHASH"
          sed -i 's/appVersion: latest/appVersion: $GITHASH' ./k8s/helm/gocolor/Chart.yaml
          # TODO: figure out how to auto version the chart using semver (probably using conventional commits)
          #"sed -i 's/version: 0.0.0/version: ${ GITHUB_SHA::8 }' k8s/helm/gocolor/Chart.yaml"
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@6018219
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: k8s/helm
          linting: off
