name: release-chart
on:
  push:
    tags: 'chart-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@6018219
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: k8s/helm
