name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Commitsar Action
        uses: aevea/commitsar@v0.15.0

#      - uses: GoogleCloudPlatform/release-please-action@v2.6.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          release-type: simple
#          package-name: gocolor

# The following works, but does not support breaking changes in the commit message indicated by `!` like `fix!: did something`
#      - name: Conventional Changelog Action
#        id: changelog
#        uses: TriPSs/conventional-changelog-action@v3
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        with:
#          github-token: ${{ secrets.github_token }}
#
#      - name: Create Release
#        uses: actions/create-release@v1
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.changelog.outputs.skipped == 'false'
#        env:
#          GITHUB_TOKEN: ${{ secrets.github_token }}
#        with:
#          tag_name: ${{ steps.changelog.outputs.tag }}
#          release_name: ${{ steps.changelog.outputs.tag }}
#          body: ${{ steps.changelog.outputs.clean_changelog }}